export const furnitureItems = [
  {
    categoryId: 1,
    type: "Sofa",
    imgUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
    description: "Comfortable and stylish seating for your living room.",
  },
  {
    categoryId: 2,
    type: "Bed",
    imgUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmVkfGVufDB8fDB8fHww",
    description: "Soft and cozy beds for a perfect night’s sleep.",
  },
  {
    categoryId: 3,
    type: "Dining Table",
    imgUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d",
    description: "Elegant dining tables to enjoy meals with family.",
  },
  {
    categoryId: 4,
    type: "Chair",
    imgUrl:
      "https://images.unsplash.com/photo-1612372606404-0ab33e7187ee?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2hhaXJ8ZW58MHx8MHx8fDA%3D",
    description: "Comfortable chairs for any room in your home.",
  },
  {
    categoryId: 5,
    type: "Wardrobe",
    imgUrl:
      "https://plus.unsplash.com/premium_photo-1670076515866-73822a3d610d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8d2FyZHJvYmV8ZW58MHx8MHx8fDA%3D",
    description: "Spacious wardrobes to organize your clothes neatly.",
  },
  {
    categoryId: 6,
    type: "TV Unit",
    imgUrl:
      "https://plus.unsplash.com/premium_photo-1681236323432-3df82be0c1b0?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VFYlMjB1bml0fGVufDB8fDB8fHww",
    description: "Modern TV units with storage and display shelves.",
  },
  {
    categoryId: 7,
    type: "Bookshelf",
    imgUrl: "https://images.unsplash.com/photo-1623018037423-b9e2179e2bfa",
    description: "Keep your books and decor organized in style.",
  },
  {
    categoryId: 8,
    type: "Coffee Table",
    imgUrl: "https://images.unsplash.com/photo-1630951839826-1e8b20780745",
    description: "Functional and decorative tables for your living area.",
  },
  {
    categoryId: 9,
    type: "Recliner",
    imgUrl: "https://images.unsplash.com/photo-1616627982702-cbf5fa4e6440",
    description: "Relax in comfort with our plush recliner chairs.",
  },
  {
    categoryId: 10,
    type: "Office Desk",
    imgUrl: "https://images.unsplash.com/photo-1587825140708-3cbe830b8e17",
    description: "Study or work in peace with our ergonomic desks.",
  },
  {
    categoryId: 11,
    type: "Nightstand",
    imgUrl: "https://images.unsplash.com/photo-1598300058312-f4f31fd6ed23",
    description: "Compact side tables to keep essentials by your bed.",
  },
  {
    categoryId: 12,
    type: "Dresser",
    imgUrl: "https://images.unsplash.com/photo-1588854337221-cb4f0417942e",
    description: "Stylish dressers to store your daily essentials.",
  },
];

export const products = [
  {
    productId: "P0001",
    categoryId: 1,
    productName: "Sofa Model 1",
    productImage:
      "https://images.unsplash.com/photo-1645527898423-a9654db8d29a?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8c29mYSUyMGltYWdlfGVufDB8fDB8fHww",
    productPrice: 7149,
    productRating: 4.3,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0002",
    categoryId: 1,
    productName: "Sofa Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 31891,
    productRating: 4.2,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0003",
    categoryId: 1,
    productName: "Sofa Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 38232,
    productRating: 4.8,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0004",
    categoryId: 1,
    productName: "Sofa Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 29651,
    productRating: 3.8,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0005",
    categoryId: 1,
    productName: "Sofa Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 30249,
    productRating: 4.5,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0006",
    categoryId: 1,
    productName: "Sofa Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 26327,
    productRating: 3.1,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0007",
    categoryId: 1,
    productName: "Sofa Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 22121,
    productRating: 4.7,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0008",
    categoryId: 1,
    productName: "Sofa Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 45054,
    productRating: 3.4,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0009",
    categoryId: 1,
    productName: "Sofa Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 35796,
    productRating: 4.0,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0010",
    categoryId: 1,
    productName: "Sofa Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Sofa",
    productPrice: 44951,
    productRating: 3.9,
    categoryType: "Sofa",
    description: "A cozy and stylish sofa perfect for any living space.",
  },
  {
    productId: "P0011",
    categoryId: 2,
    productName: "Bed Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 26693,
    productRating: 3.6,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0012",
    categoryId: 2,
    productName: "Bed Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 11000,
    productRating: 3.7,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0013",
    categoryId: 2,
    productName: "Bed Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 5180,
    productRating: 3.6,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0014",
    categoryId: 2,
    productName: "Bed Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 16513,
    productRating: 3.5,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0015",
    categoryId: 2,
    productName: "Bed Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 6150,
    productRating: 3.6,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0016",
    categoryId: 2,
    productName: "Bed Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 8924,
    productRating: 4.9,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0017",
    categoryId: 2,
    productName: "Bed Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 8624,
    productRating: 3.5,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0018",
    categoryId: 2,
    productName: "Bed Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 31360,
    productRating: 4.2,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0019",
    categoryId: 2,
    productName: "Bed Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 39246,
    productRating: 3.8,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0020",
    categoryId: 2,
    productName: "Bed Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Bed",
    productPrice: 34586,
    productRating: 3.4,
    categoryType: "Bed",
    description:
      "A comfortable bed built for restful nights and modern design.",
  },
  {
    productId: "P0021",
    categoryId: 3,
    productName: "Dining Table Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 23053,
    productRating: 4.8,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0022",
    categoryId: 3,
    productName: "Dining Table Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 11184,
    productRating: 5.0,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0023",
    categoryId: 3,
    productName: "Dining Table Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 44764,
    productRating: 4.4,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0024",
    categoryId: 3,
    productName: "Dining Table Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 43761,
    productRating: 3.3,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0025",
    categoryId: 3,
    productName: "Dining Table Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 24984,
    productRating: 3.5,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0026",
    categoryId: 3,
    productName: "Dining Table Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 38321,
    productRating: 3.6,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0027",
    categoryId: 3,
    productName: "Dining Table Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 38078,
    productRating: 3.6,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0028",
    categoryId: 3,
    productName: "Dining Table Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 12788,
    productRating: 4.2,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0029",
    categoryId: 3,
    productName: "Dining Table Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 14098,
    productRating: 4.2,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0030",
    categoryId: 3,
    productName: "Dining Table Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Dining+Table",
    productPrice: 10963,
    productRating: 4.6,
    categoryType: "Dining Table",
    description: "Elegant dining tables to gather and enjoy meals.",
  },
  {
    productId: "P0031",
    categoryId: 4,
    productName: "Chair Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 38879,
    productRating: 3.6,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0032",
    categoryId: 4,
    productName: "Chair Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 9394,
    productRating: 3.1,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0033",
    categoryId: 4,
    productName: "Chair Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 28224,
    productRating: 4.1,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0034",
    categoryId: 4,
    productName: "Chair Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 11625,
    productRating: 3.3,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0035",
    categoryId: 4,
    productName: "Chair Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 49939,
    productRating: 3.5,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0036",
    categoryId: 4,
    productName: "Chair Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 39175,
    productRating: 4.9,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0037",
    categoryId: 4,
    productName: "Chair Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 39326,
    productRating: 3.2,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0038",
    categoryId: 4,
    productName: "Chair Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 45428,
    productRating: 3.5,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0039",
    categoryId: 4,
    productName: "Chair Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 14816,
    productRating: 3.7,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0040",
    categoryId: 4,
    productName: "Chair Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Chair",
    productPrice: 30248,
    productRating: 4.1,
    categoryType: "Chair",
    description: "Supportive and sleek chairs that fit any setting.",
  },
  {
    productId: "P0041",
    categoryId: 5,
    productName: "Wardrobe Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 6849,
    productRating: 3.2,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0042",
    categoryId: 5,
    productName: "Wardrobe Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 24988,
    productRating: 4.3,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0043",
    categoryId: 5,
    productName: "Wardrobe Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 25121,
    productRating: 4.1,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0044",
    categoryId: 5,
    productName: "Wardrobe Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 5427,
    productRating: 3.2,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0045",
    categoryId: 5,
    productName: "Wardrobe Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 15306,
    productRating: 4.0,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0046",
    categoryId: 5,
    productName: "Wardrobe Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 21193,
    productRating: 4.0,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0047",
    categoryId: 5,
    productName: "Wardrobe Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 8531,
    productRating: 4.2,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0048",
    categoryId: 5,
    productName: "Wardrobe Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 5956,
    productRating: 3.4,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0049",
    categoryId: 5,
    productName: "Wardrobe Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 18569,
    productRating: 4.4,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0050",
    categoryId: 5,
    productName: "Wardrobe Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Wardrobe",
    productPrice: 30468,
    productRating: 3.8,
    categoryType: "Wardrobe",
    description: "Spacious wardrobes to organize your essentials.",
  },
  {
    productId: "P0051",
    categoryId: 6,
    productName: "TV Unit Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 38300,
    productRating: 4.4,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0052",
    categoryId: 6,
    productName: "TV Unit Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 36184,
    productRating: 3.3,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0053",
    categoryId: 6,
    productName: "TV Unit Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 32282,
    productRating: 4.6,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0054",
    categoryId: 6,
    productName: "TV Unit Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 25564,
    productRating: 3.0,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0055",
    categoryId: 6,
    productName: "TV Unit Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 25854,
    productRating: 4.0,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0056",
    categoryId: 6,
    productName: "TV Unit Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 7814,
    productRating: 3.6,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0057",
    categoryId: 6,
    productName: "TV Unit Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 11601,
    productRating: 4.1,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0058",
    categoryId: 6,
    productName: "TV Unit Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 10020,
    productRating: 4.0,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0059",
    categoryId: 6,
    productName: "TV Unit Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 11532,
    productRating: 3.7,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0060",
    categoryId: 6,
    productName: "TV Unit Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=TV+Unit",
    productPrice: 37856,
    productRating: 4.2,
    categoryType: "TV Unit",
    description: "Contemporary TV units to enhance your living room.",
  },
  {
    productId: "P0061",
    categoryId: 7,
    productName: "Bookshelf Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 19614,
    productRating: 4.7,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0062",
    categoryId: 7,
    productName: "Bookshelf Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 13668,
    productRating: 5.0,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0063",
    categoryId: 7,
    productName: "Bookshelf Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 30987,
    productRating: 4.2,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0064",
    categoryId: 7,
    productName: "Bookshelf Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 18084,
    productRating: 3.6,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0065",
    categoryId: 7,
    productName: "Bookshelf Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 27339,
    productRating: 3.4,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0066",
    categoryId: 7,
    productName: "Bookshelf Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 14894,
    productRating: 4.7,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0067",
    categoryId: 7,
    productName: "Bookshelf Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 34369,
    productRating: 4.8,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0068",
    categoryId: 7,
    productName: "Bookshelf Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 28414,
    productRating: 4.4,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0069",
    categoryId: 7,
    productName: "Bookshelf Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 23499,
    productRating: 4.9,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0070",
    categoryId: 7,
    productName: "Bookshelf Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Bookshelf",
    productPrice: 38389,
    productRating: 3.1,
    categoryType: "Bookshelf",
    description: "Stylish bookshelves to showcase your collection.",
  },
  {
    productId: "P0071",
    categoryId: 8,
    productName: "Coffee Table Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 22956,
    productRating: 4.7,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0072",
    categoryId: 8,
    productName: "Coffee Table Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 45697,
    productRating: 3.6,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0073",
    categoryId: 8,
    productName: "Coffee Table Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 32968,
    productRating: 3.4,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0074",
    categoryId: 8,
    productName: "Coffee Table Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 46403,
    productRating: 3.8,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0075",
    categoryId: 8,
    productName: "Coffee Table Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 20274,
    productRating: 4.1,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0076",
    categoryId: 8,
    productName: "Coffee Table Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 20776,
    productRating: 3.7,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0077",
    categoryId: 8,
    productName: "Coffee Table Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 11608,
    productRating: 4.5,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0078",
    categoryId: 8,
    productName: "Coffee Table Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 32344,
    productRating: 3.7,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0079",
    categoryId: 8,
    productName: "Coffee Table Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 44368,
    productRating: 4.3,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0080",
    categoryId: 8,
    productName: "Coffee Table Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Coffee+Table",
    productPrice: 37576,
    productRating: 3.0,
    categoryType: "Coffee Table",
    description: "Compact coffee tables for relaxing moments.",
  },
  {
    productId: "P0081",
    categoryId: 9,
    productName: "Recliner Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 43725,
    productRating: 4.0,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0082",
    categoryId: 9,
    productName: "Recliner Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 25367,
    productRating: 4.2,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0083",
    categoryId: 9,
    productName: "Recliner Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 29144,
    productRating: 4.2,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0084",
    categoryId: 9,
    productName: "Recliner Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 7338,
    productRating: 4.5,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0085",
    categoryId: 9,
    productName: "Recliner Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 11645,
    productRating: 4.8,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0086",
    categoryId: 9,
    productName: "Recliner Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 12150,
    productRating: 4.8,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0087",
    categoryId: 9,
    productName: "Recliner Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 21044,
    productRating: 3.6,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0088",
    categoryId: 9,
    productName: "Recliner Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 37138,
    productRating: 4.0,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0089",
    categoryId: 9,
    productName: "Recliner Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 42988,
    productRating: 4.8,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0090",
    categoryId: 9,
    productName: "Recliner Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Recliner",
    productPrice: 10801,
    productRating: 4.7,
    categoryType: "Recliner",
    description: "Comfortable recliners for your lounging needs.",
  },
  {
    productId: "P0091",
    categoryId: 10,
    productName: "Office Desk Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 29036,
    productRating: 4.3,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0092",
    categoryId: 10,
    productName: "Office Desk Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 21812,
    productRating: 3.1,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0093",
    categoryId: 10,
    productName: "Office Desk Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 48058,
    productRating: 3.1,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0094",
    categoryId: 10,
    productName: "Office Desk Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 33131,
    productRating: 3.6,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0095",
    categoryId: 10,
    productName: "Office Desk Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 40468,
    productRating: 4.2,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0096",
    categoryId: 10,
    productName: "Office Desk Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 23272,
    productRating: 3.6,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0097",
    categoryId: 10,
    productName: "Office Desk Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 28119,
    productRating: 4.9,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0098",
    categoryId: 10,
    productName: "Office Desk Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 46426,
    productRating: 3.7,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0099",
    categoryId: 10,
    productName: "Office Desk Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 36084,
    productRating: 5.0,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0100",
    categoryId: 10,
    productName: "Office Desk Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Office+Desk",
    productPrice: 40866,
    productRating: 4.5,
    categoryType: "Office Desk",
    description: "Functional desks designed for productivity.",
  },
  {
    productId: "P0101",
    categoryId: 11,
    productName: "Nightstand Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 28898,
    productRating: 4.2,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0102",
    categoryId: 11,
    productName: "Nightstand Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 23672,
    productRating: 3.7,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0103",
    categoryId: 11,
    productName: "Nightstand Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 34862,
    productRating: 4.4,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0104",
    categoryId: 11,
    productName: "Nightstand Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 28245,
    productRating: 4.9,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0105",
    categoryId: 11,
    productName: "Nightstand Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 49852,
    productRating: 4.7,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0106",
    categoryId: 11,
    productName: "Nightstand Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 8680,
    productRating: 3.8,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0107",
    categoryId: 11,
    productName: "Nightstand Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 20709,
    productRating: 3.2,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0108",
    categoryId: 11,
    productName: "Nightstand Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 43867,
    productRating: 4.4,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0109",
    categoryId: 11,
    productName: "Nightstand Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 30134,
    productRating: 4.3,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0110",
    categoryId: 11,
    productName: "Nightstand Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Nightstand",
    productPrice: 39722,
    productRating: 4.1,
    categoryType: "Nightstand",
    description: "Handy nightstands to keep your essentials close.",
  },
  {
    productId: "P0111",
    categoryId: 12,
    productName: "Dresser Model 1",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 25012,
    productRating: 3.4,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0112",
    categoryId: 12,
    productName: "Dresser Model 2",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 6140,
    productRating: 4.1,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0113",
    categoryId: 12,
    productName: "Dresser Model 3",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 9904,
    productRating: 4.6,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0114",
    categoryId: 12,
    productName: "Dresser Model 4",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 29684,
    productRating: 3.2,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0115",
    categoryId: 12,
    productName: "Dresser Model 5",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 23469,
    productRating: 4.9,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0116",
    categoryId: 12,
    productName: "Dresser Model 6",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 13274,
    productRating: 3.7,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0117",
    categoryId: 12,
    productName: "Dresser Model 7",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 47392,
    productRating: 3.6,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0118",
    categoryId: 12,
    productName: "Dresser Model 8",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 11106,
    productRating: 3.2,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0119",
    categoryId: 12,
    productName: "Dresser Model 9",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 21121,
    productRating: 5.0,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
  {
    productId: "P0120",
    categoryId: 12,
    productName: "Dresser Model 10",
    productImage: "https://via.placeholder.com/300x200.png?text=Dresser",
    productPrice: 20336,
    productRating: 4.3,
    categoryType: "Dresser",
    description: "Beautiful dressers for stylish storage.",
  },
];
